import { ExternalLink } from "lucide-react";
import type { Metadata } from "next";
import { AdSlot } from "../../components/AdSlot";
import { PageHero } from "../../components/PageHero";

export const metadata: Metadata = { title: "Documentos para Beca 18: cómo organizar tu revisión", description: "Guía independiente para organizar documentos y comprobar qué exige la modalidad vigente de Beca 18." };

export default function DocumentsGuide() {
  return (
    <main>
      <PageHero eyebrow="Guía de organización" title="No empieces por subir archivos: empieza por leer tu modalidad." description="Los documentos dependen de la convocatoria y la situación de cada postulante. Utiliza esta guía como método de revisión." />
      <section className="section"><div className="site-container content-layout"><article className="card article rich-copy"><h2>1. Crea tu lista desde las bases</h2><p>No copies el checklist de otra persona. Abre las bases correspondientes al año y modalidad correctos. Anota cada requisito, la forma de acreditarlo, la vigencia exigida y la etapa en la que debe presentarse.</p><h2>2. Separa documentos por función</h2><ul><li><strong>Identificación:</strong> información necesaria para reconocer al postulante.</li><li><strong>Estudios:</strong> documentos o registros que acreditan secundaria y rendimiento.</li><li><strong>Condición de la modalidad:</strong> evidencia específica de la situación económica o especial.</li><li><strong>Ingreso:</strong> constancia emitida por una institución elegible cuando sea requerida.</li><li><strong>Declaraciones y formatos:</strong> documentos generados por el módulo oficial.</li></ul><AdSlot /><h2>3. Verifica antes de enviar</h2><p>Comprueba que nombres, fechas, institución, sede, carrera y periodo coincidan. Asegúrate de que el archivo sea legible, completo y corresponda al documento solicitado. No edites ni alteres documentos oficiales.</p><h2>4. Protege tus datos</h2><p>No envíes DNI, contraseña, constancias o códigos a páginas que prometen realizar el trámite por ti. RutaBeca no solicita archivos personales. Utiliza únicamente el módulo señalado en la convocatoria oficial y conserva tu constancia de registro.</p><h2>5. Guarda evidencia del proceso</h2><p>Descarga cargos, constancias y comunicaciones oficiales. Nombra los archivos con claridad y conserva una copia en un lugar seguro. Si la entidad permite subsanar una observación, revisa el plazo y el canal autorizado.</p><div className="source-box"><strong>Verificación final:</strong> abre <a href="https://www.pronabec.gob.pe/beca-18/" target="_blank" rel="noopener noreferrer">la página oficial de Beca 18 <ExternalLink size={15} style={{ display: "inline" }} /></a> y descarga las bases correspondientes.</div></article><aside className="sidebar"><div className="card side-card"><h2>RutaBeca no almacena documentos</h2><p>Esta primera versión protege tu privacidad usando únicamente listas educativas.</p></div><div className="card side-card"><h2>Regla principal</h2><p>Si una captura contradice las bases, utiliza las bases y consulta a la entidad.</p></div></aside></div></section>
    </main>
  );
}
