import type { Metadata } from "next";
import Link from "next/link";
import { AdSlot } from "../../components/AdSlot";
import { PageHero } from "../../components/PageHero";

export const metadata: Metadata = { title: "Razonamiento matemático: proporciones y porcentajes", description: "Lección gratuita con ejemplos originales de proporciones, porcentajes y lectura de problemas." };

export default function MathLesson() {
  return (
    <main>
      <PageHero eyebrow="Academia · Matemática" title="Convierte una situación en pasos que puedas comprobar." description="Practica proporciones y porcentajes entendiendo qué representa cada número." />
      <section className="section"><div className="site-container content-layout"><article className="card article rich-copy"><h2>1. Lee las cantidades con sus unidades</h2><p>Un número sin contexto puede confundirte. Escribe siempre qué representa: soles, estudiantes, preguntas o minutos. Si tres cuadernos cuestan S/ 24, el valor unitario se obtiene dividiendo S/ 24 entre 3 cuadernos. El resultado es S/ 8 por cuaderno.</p><h2>2. Reconoce una proporción directa</h2><p>Dos cantidades son directamente proporcionales cuando aumentan o disminuyen manteniendo la misma razón. Si cada cuaderno cuesta S/ 8, entonces cinco cuadernos cuestan 5 × 8 = S/ 40. Antes de aplicar una regla, confirma que el precio unitario realmente sea constante.</p><div className="source-box"><strong>Ejemplo:</strong> 12 preguntas se resuelven en 18 minutos a ritmo constante. El tiempo por pregunta es 18 ÷ 12 = 1,5 minutos. Para 20 preguntas: 20 × 1,5 = 30 minutos.</div><AdSlot /><h2>3. Calcula un porcentaje desde el valor inicial</h2><p>Para hallar el cambio porcentual, resta el valor inicial al final y divide el cambio entre el valor inicial. Si un puntaje aumenta de 80 a 100, el cambio es 20. Luego 20 ÷ 80 = 0,25. Multiplicado por 100, el aumento es 25 %.</p><p>Un error frecuente es dividir entre el valor final. El porcentaje de cambio siempre toma como referencia el valor inicial, salvo que el problema indique otra base.</p><h2>4. Traduce antes de operar</h2><p>Subraya la pregunta exacta y organiza los datos. Después decide la operación. Esta pausa evita multiplicar solo porque aparecen dos números. Un problema bien resuelto debe permitir explicar por qué se utilizó cada operación.</p><h2>Práctica</h2><ol><li>Cuatro materiales cuestan S/ 36. ¿Cuánto cuestan siete al mismo precio?</li><li>Un grupo pasa de 120 a 150 participantes. ¿Cuál es el aumento porcentual?</li><li>Se responden 15 preguntas en 24 minutos. ¿Cuánto tardarían 25 al mismo ritmo?</li></ol><p><strong>Resultados:</strong> S/ 63; 25 %; 40 minutos. Comprueba las unidades en cada paso.</p><h2>Lista de verificación</h2><ul><li>¿Escribí qué representa cada cantidad?</li><li>¿La relación es realmente proporcional?</li><li>¿Usé el valor inicial como base del porcentaje?</li><li>¿El resultado tiene una unidad razonable?</li><li>¿Puedo explicar el procedimiento sin repetir solo la fórmula?</li></ul></article><aside className="sidebar"><div className="card side-card"><h2>Ponlo en práctica</h2><p>El simulacro incluye problemas de proporciones, ecuaciones y porcentajes.</p><Link className="btn btn-ghost" style={{ marginTop: ".8rem" }} href="/simulacros">Resolver preguntas</Link></div><div className="card side-card"><h2>Volver a Academia</h2><Link href="/academia" style={{ color: "var(--blue-2)", fontWeight: 850 }}>Ver todas las rutas →</Link></div></aside></div></section>
    </main>
  );
}
